<!DOCTYPE html>
<html>
<style>
.myDiv {
  border: 5px outset red;
  background-color: lightblue;
  text-align: center;
}
</style>
<head>
<title>Hotel Reservation Reminder</title>
</head>
<body>
<div class="myDiv">
	<h3>Dear ${firstName},</h3>

	<p>This is a reminder that you have a booking at ${hotelName} on ${date} </p>
	<p>Good day</p>
	
	<p>Regards</p>
	<p>Tokyu Team</p>
</div>
</body>
</html>
